### ISSUE TITLE
Fix broken images

### ISSUE THREAD

**Issue by TriinK** [Kashish1904/mummydadhaba1.0#2]
Please assign me this issue of fixing broken images on this webpage.

**Comment by Kashish1904** [comment]
Can you please add more details, like which images are broken.

**Comment by TriinK** [comment]
![image](https://user-images.githubusercontent.com/33719534/195656582-2880541f-00f7-4c61-b4e2-95fdd713f9ff.png)
This one for example but it seems to me that the link provided in Readme has an older version deployed than the code is.

**Comment by Kashish1904** [comment]
Yes you got it, code is ok. Deployed version is older.
