### ISSUE TITLE
Enhancing the UI of suggestions page.

### ISSUE THREAD

**Issue by Mahak008** [Kashish1904/mummydadhaba1.0#5]
Kindly assign this issue to me.

**Comment by Kashish1904** [comment]
Great work pointing that out @Mahak008.

**Comment by Mahak008** [comment]
Hi, @Kashish1904 
I have cloned this repo, but i am getting 2 errors when i click on send button on suggestions page. so, should I keep on editing ?
![Screenshot (332)](https://user-images.githubusercontent.com/88129955/195902366-1e45fff1-6455-42e5-9407-d069eafd181b.png)
